version: "3.4"

# Development environment override
services:
  php:
    build:
      target: symfony_php_dev
    volumes:
      - ./:/srv/app:rw,cached
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      # - ./var:/srv/app/var:rw
    environment:
      APP_ENV: dev
      # If you develop on Linux, uncomment and set the following vars to use those UID/GID for php container commands
      # HOST_UID: 1000
      # HOST_GID: 1000

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro
